import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, LogOut, Ticket } from 'lucide-react';
import { listMyBookings } from '../api/booking';
import { formatCinemaDate, formatCinemaTime } from '../data/cinema';
import { useStore } from '../store/useStore';
import MovieTile from '../components/MovieTile';

export default function AccountPage() {
  const user = useStore((state) => state.user); const favorites = useStore((state) => state.favorites); const watchlist = useStore((state) => state.watchlist); const history = useStore((state) => state.history); const signOut = useStore((state) => state.signOut); const [bookings, setBookings] = useState([]); const [tab, setTab] = useState('tickets');
  useEffect(() => { listMyBookings().then(setBookings); }, []);
  if (!user) { const guestTab = tab === 'tickets' ? 'favorites' : tab; const localMovies = guestTab === 'favorites' ? favorites : guestTab === 'watchlist' ? watchlist : history; return <div className="account-page account-page--guest"><header><div><p>ARCHIVO LOCAL</p><h1>TUS PELÍCULAS VIAJAN CONTIGO.</h1><span>Tu lista permanece en este dispositivo; inicia sesión para sincronizarla.</span></div><Link className="button-primary" to="/acceso?returnTo=/cuenta">SINCRONIZAR ARCHIVO</Link></header><nav>{[['favorites',`FAVORITOS ${favorites.length}`],['watchlist',`POR VER ${watchlist.length}`],['history',`HISTORIAL ${history.length}`]].map(([id,label]) => <button key={id} className={guestTab === id ? 'is-active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav><section className="account-movies">{localMovies.length ? localMovies.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>Tu archivo espera su primera película</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section></div>; }
  return <div className="account-page"><header><div><p>ARCHIVO PERSONAL</p><h1>HOLA, {user.name?.toUpperCase()}</h1><span>{user.email}</span></div><button onClick={signOut}><LogOut size={16} />CERRAR SESIÓN</button></header><nav>{[['tickets',`ENTRADAS ${bookings.length}`],['favorites',`FAVORITOS ${favorites.length}`],['watchlist',`POR VER ${watchlist.length}`],['history',`HISTORIAL ${history.length}`]].map(([id,label]) => <button key={id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav>{tab === 'tickets' && <section className="ticket-list">{bookings.length ? bookings.map((booking) => { const showing = booking.showing || booking.cinema_showings || {}; return <article key={booking.id}><div className="ticket-list__mark"><Ticket size={22} /></div><div><span>{booking.reference || 'CINE DEMO'} · {booking.operation === 'reservation' || booking.status === 'reserved_demo' ? 'RESERVA' : 'COMPRA'}</span><h2>{showing.movie?.title || showing.Pelicula?.titulo || 'Función CINE'}</h2><p><CalendarDays size={14} />{showing.starts_at ? `${formatCinemaDate(showing.starts_at)} · ${formatCinemaTime(showing.starts_at)}` : 'Función confirmada'}</p></div><strong>{(booking.seat_ids || booking.cinema_booking_items?.map((item) => item.seat_id) || []).join(' · ')}</strong></article>; }) : <div className="account-empty"><Ticket size={30} /><h2>Todavía no hay entradas</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section>}{tab === 'favorites' && <section className="account-movies">{favorites.length ? favorites.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>Tu archivo espera su primera película</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section>}{tab === 'watchlist' && <section className="account-movies">{watchlist.length ? watchlist.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>No has añadido películas por ver</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section>}{tab === 'history' && <section className="account-movies">{history.length ? history.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>Tu historial está vacío</h2><Link to="/cartelera">Descubrir una película</Link></div>}</section>}</div>;
}
