import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { LogOut, Ticket } from 'lucide-react';
import { listMyBookings } from '../api/booking';
import { useStore } from '../store/useStore';
import MovieTile from '../components/MovieTile';
import SeriesCard from '../components/SeriesCard';
import CinemaTicket from '../components/CinemaTicket';

export default function AccountPage() {
  const collectionError = useStore((state) => state.collectionError);
  const loadCollections = useStore((state) => state.loadCollections);
  const user = useStore((state) => state.user); const favorites = useStore((state) => state.favorites); const watchlist = useStore((state) => state.watchlist); const seriesWatchlist = useStore((state) => state.seriesWatchlist); const history = useStore((state) => state.history); const signOutAction = useStore((state) => state.signOut); const [bookings, setBookings] = useState([]); const [tab, setTab] = useState('tickets');
  useEffect(() => { let active = true; listMyBookings().then((items) => { if (active) setBookings(items); }).catch(() => { if (active) useStore.setState({ collectionError: 'No pudimos cargar tus entradas. Vuelve a intentarlo.' }); }); return () => { active = false; }; }, [user?.id]);
  const signOut = async () => { try { await signOutAction(); } catch (error) { useStore.setState({ collectionError: error.message || 'No pudimos cerrar la sesión. Reintenta.' }); } };
  if (!user) { const guestTab = tab === 'tickets' ? 'favorites' : tab; const localMovies = guestTab === 'favorites' ? favorites : guestTab === 'watchlist' ? watchlist : history; return <div className="account-page account-page--guest"><header><div><p>ARCHIVO LOCAL</p><h1>TUS HISTORIAS VIAJAN CONTIGO.</h1><span>Tu lista permanece en este dispositivo; inicia sesión para sincronizarla.</span></div><Link className="button-primary" to="/acceso?returnTo=/cuenta">SINCRONIZAR ARCHIVO</Link></header><nav>{[['favorites',`FAVORITOS ${favorites.length}`],['watchlist',`PELÍCULAS POR VER ${watchlist.length}`],['series',`SERIES POR VER ${seriesWatchlist.length}`],['history',`HISTORIAL ${history.length}`]].map(([id,label]) => <button key={id} className={guestTab === id ? 'is-active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav>{guestTab === 'series' ? <section className="account-series">{seriesWatchlist.length ? seriesWatchlist.map((series) => <SeriesCard key={series.id} series={series} />) : <div className="account-empty"><h2>Tu próxima serie todavía no está aquí</h2><Link to="/series">Explorar series</Link></div>}</section> : <section className="account-movies">{localMovies.length ? localMovies.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>Tu archivo espera su primera película</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section>}</div>; }
  return <div className="account-page">{collectionError && <p className="collection-warning" role="status">{collectionError} <button onClick={() => loadCollections()}>REINTENTAR</button></p>}<header><div><p>ARCHIVO PERSONAL</p><h1>HOLA, {user.name?.toUpperCase()}</h1><span>{user.email}</span></div><button onClick={signOut}><LogOut size={16} />CERRAR SESIÓN</button></header><nav>{[['tickets',`ENTRADAS ${bookings.length}`],['favorites',`FAVORITOS ${favorites.length}`],['watchlist',`PELÍCULAS POR VER ${watchlist.length}`],['series',`SERIES POR VER ${seriesWatchlist.length}`],['history',`HISTORIAL ${history.length}`]].map(([id,label]) => <button key={id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav>{tab === 'tickets' && <section className="ticket-list">{bookings.length ? bookings.map((booking) => { const showing = booking.showing || booking.cinema_showings || {}; return <CinemaTicket key={booking.id} compact total={booking.total} showing={showing} seatIds={booking.seat_ids || booking.cinema_booking_items?.map((item) => item.seat_id) || []} reference={booking.reference || 'CINE DEMO'} operation={booking.operation === 'reservation' || booking.status === 'reserved_demo' ? 'reservation' : 'purchase'} />; }) : <div className="account-empty"><Ticket size={30} /><h2>Todavía no hay entradas</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section>}{tab === 'favorites' && <section className="account-movies">{favorites.length ? favorites.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>Tu archivo espera su primera película</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section>}{tab === 'watchlist' && <section className="account-movies">{watchlist.length ? watchlist.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>No has añadido películas por ver</h2><Link to="/cartelera">Explorar cartelera</Link></div>}</section>}{tab === 'series' && <section className="account-series">{seriesWatchlist.length ? seriesWatchlist.map((series) => <SeriesCard key={series.id} series={series} />) : <div className="account-empty"><h2>No has añadido series por ver</h2><Link to="/series">Explorar series</Link></div>}</section>}{tab === 'history' && <section className="account-movies">{history.length ? history.map((movie, index) => <MovieTile key={movie.id} movie={movie} index={index} />) : <div className="account-empty"><h2>Tu historial está vacío</h2><Link to="/cartelera">Descubrir una película</Link></div>}</section>}</div>;
}
