import ProjectionLoader from '../components/ProjectionLoader';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Check, Clock3, LoaderCircle, ShieldCheck } from 'lucide-react';
import { confirmDemoBooking, getHold, remainingHoldSeconds, releaseHold } from '../api/booking';
import { formatCOP } from '../data/cinema';
import { useStore } from '../store/useStore';
import BookingSteps from '../components/BookingSteps';
import CinemaTicket from '../components/CinemaTicket';

export default function CheckoutPage() {
  const { holdId } = useParams(); const navigate = useNavigate(); const [params] = useSearchParams(); const user = useStore((state) => state.user); const [operation, setOperation] = useState(params.get('operation') === 'reservation' ? 'reservation' : 'purchase'); const [hold, setHold] = useState(null); const [seconds, setSeconds] = useState(0); const [accepted, setAccepted] = useState(false); const [loading, setLoading] = useState(false); const [booking, setBooking] = useState(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; getHold(holdId).then((item) => { if (!active) return; setHold(item); setSeconds(item ? remainingHoldSeconds(item.expires_at) : 0); if (!item) setError('No encontramos esta reserva temporal. Selecciona una función para continuar.'); }).catch(() => { if (active) setError('No pudimos recuperar tu reserva. Vuelve a intentarlo desde la sala.'); }); return () => { active = false; }; }, [holdId]);
  useEffect(() => { if (!hold || booking) return undefined; const timer = setInterval(() => { const remaining = remainingHoldSeconds(hold.expires_at); setSeconds(remaining); if (!remaining) { clearInterval(timer); setError('La reserva temporal expiró. Regresa a la sala para elegir de nuevo.'); } }, 1000); return () => clearInterval(timer); }, [hold, booking]);
  const confirm = async () => { setLoading(true); setError(''); try { setBooking(await confirmDemoBooking(holdId, operation, { name: user?.name, email: user?.email })); } catch (confirmError) { setError(confirmError.message); } finally { setLoading(false); } };
  if (booking) return <div className="booking-success"><div className="success-ticket"><span className="success-ticket__icon"><Check size={30} /></span><p>{operation === 'reservation' ? 'RESERVA CONFIRMADA' : 'COMPRA CONFIRMADA'}</p><h1>NOS VEMOS<br /><em>EN LA OSCURIDAD.</em></h1><CinemaTicket showing={booking.showing || hold?.showing} seatIds={booking.seat_ids || hold?.seat_ids || []} total={hold?.total} reference={booking.reference} operation={operation} /><p className="demo-notice">{operation === 'reservation' ? 'Reserva registrada sin cobro.' : 'Compra de demostración · no se realizó ningún cobro.'}</p><Link to="/cuenta" className="button-primary">VER MIS ENTRADAS</Link></div></div>;
  if (!hold && error) return <div className="catalog-empty" role="alert"><h1>RESERVA NO DISPONIBLE</h1><p>{error}</p><Link to="/cartelera">VOLVER A CARTELERA</Link></div>;
  if (!hold) return <ProjectionLoader label="Recuperando tu reserva" full />;
  const showing = hold.showing || hold.cinema_showings || {};
  const seatIds = hold.seat_ids || hold.cinema_hold_seats?.map((item) => item.seat_id) || [];
  const unitPrice = seatIds.length ? hold.total / seatIds.length : 0;
  return <div className="checkout-page"><header className="booking-header"><button onClick={async () => { await releaseHold(holdId); navigate(`/funcion/${hold.showing_id}/asientos`); }}>LIBERAR Y VOLVER</button><BookingSteps active={2} /><span className={`booking-timer ${seconds < 120 ? 'is-low' : ''}`}><Clock3 size={14} />{String(Math.floor(seconds / 60)).padStart(2,'0')}:{String(seconds % 60).padStart(2,'0')}</span></header><main className="checkout-layout"><section><p className="checkout-kicker">OPERACIÓN SEGURA · DEMO</p><h1>ÚLTIMO<br /><em>FOTOGRAMA.</em></h1><div className="operation-switch" aria-label="Tipo de operación"><button className={operation === 'reservation' ? 'is-active' : ''} onClick={() => { setOperation('reservation'); setAccepted(false); }}>RESERVAR</button><button className={operation === 'purchase' ? 'is-active' : ''} onClick={() => { setOperation('purchase'); setAccepted(false); }}>COMPRAR</button></div><CinemaTicket showing={showing} seatIds={seatIds} total={hold.total} reference={`HOLD ${holdId.slice(0, 8).toUpperCase()}`} operation={operation} /><div className="checkout-card"><div><span>CLIENTE</span><strong>{user?.name} · {user?.email}</strong></div><div><span>PRECIO UNITARIO</span><strong>{formatCOP(unitPrice)}</strong></div></div><label className="terms-check"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} /><span><Check size={14} /></span><p>Acepto confirmar esta {operation === 'reservation' ? 'reserva' : 'compra de demostración'}{operation === 'purchase' ? ' y entiendo que no se realizará ningún cobro.' : '.'}</p></label>{error && <p className="booking-error">{error}</p>}</section><aside className="checkout-total"><ShieldCheck size={28} /><p>RESUMEN</p><div><span>Cantidad</span><strong>{seatIds.length} ticket{seatIds.length === 1 ? '' : 's'}</strong></div><div><span>Precio unitario</span><strong>{formatCOP(unitPrice)}</strong></div><div><span>Servicio</span><strong>{formatCOP(0)}</strong></div><div className="checkout-total__grand"><span>TOTAL</span><strong>{formatCOP(hold.total)}</strong></div><button className="button-primary" disabled={!accepted || loading || seconds === 0} onClick={confirm}>{loading ? <LoaderCircle className="animate-spin" size={17} /> : <ShieldCheck size={17} />}CONFIRMAR {operation === 'reservation' ? 'RESERVA' : 'COMPRA'}</button><small>{operation === 'reservation' ? 'Las sillas quedarán reservadas.' : 'Transacción simulada. Las sillas quedarán vendidas.'}</small></aside></main></div>;
}
