import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Check, Clock3, LoaderCircle, ShieldCheck, Ticket } from 'lucide-react';
import { confirmDemoBooking, getHold, remainingHoldSeconds, releaseHold } from '../api/booking';
import { formatCinemaDate, formatCinemaTime, formatCOP } from '../data/cinema';
import { useStore } from '../store/useStore';

export default function CheckoutPage() {
  const { holdId } = useParams(); const navigate = useNavigate(); const [params] = useSearchParams(); const user = useStore((state) => state.user); const [operation, setOperation] = useState(params.get('operation') === 'reservation' ? 'reservation' : 'purchase'); const [hold, setHold] = useState(null); const [seconds, setSeconds] = useState(0); const [accepted, setAccepted] = useState(false); const [loading, setLoading] = useState(false); const [booking, setBooking] = useState(null); const [error, setError] = useState('');
  useEffect(() => { getHold(holdId).then((item) => { setHold(item); setSeconds(item ? remainingHoldSeconds(item.expires_at) : 0); }); }, [holdId]);
  useEffect(() => { if (!hold || booking) return undefined; const timer = setInterval(() => { const remaining = remainingHoldSeconds(hold.expires_at); setSeconds(remaining); if (!remaining) { clearInterval(timer); setError('La reserva temporal expiró. Regresa a la sala para elegir de nuevo.'); } }, 1000); return () => clearInterval(timer); }, [hold, booking]);
  const confirm = async () => { setLoading(true); setError(''); try { setBooking(await confirmDemoBooking(holdId, operation, { name: user?.name, email: user?.email })); } catch (confirmError) { setError(confirmError.message); } finally { setLoading(false); } };
  if (booking) return <div className="booking-success"><div className="success-ticket"><span className="success-ticket__icon"><Check size={30} /></span><p>{operation === 'reservation' ? 'RESERVA CONFIRMADA' : 'COMPRA CONFIRMADA'}</p><h1>NOS VEMOS<br /><em>EN LA OSCURIDAD.</em></h1><div className="ticket-code"><span>REFERENCIA</span><strong>{booking.reference}</strong></div><div className="ticket-stub"><Ticket size={26} /><div><strong>{booking.showing?.movie?.title || hold?.showing?.movie?.title}</strong><span>{(booking.seat_ids || hold?.seat_ids || []).join(' · ')}</span></div></div><p className="demo-notice">{operation === 'reservation' ? 'Reserva registrada sin cobro.' : 'Compra de demostración · no se realizó ningún cobro.'}</p><Link to="/cuenta" className="button-primary">VER MIS ENTRADAS</Link></div></div>;
  if (!hold) return <div className="cinema-loading"><span>CINE</span><p>Recuperando tu reserva</p></div>;
  const showing = hold.showing || hold.cinema_showings || {};
  const seatIds = hold.seat_ids || hold.cinema_hold_seats?.map((item) => item.seat_id) || [];
  const unitPrice = seatIds.length ? hold.total / seatIds.length : 0;
  return <div className="checkout-page"><header className="booking-header"><button onClick={async () => { await releaseHold(holdId); navigate(`/funcion/${hold.showing_id}/asientos`); }}>LIBERAR Y VOLVER</button><div><span>PASO 2 DE 2</span><strong>CONFIRMACIÓN</strong></div><span className={`booking-timer ${seconds < 120 ? 'is-low' : ''}`}><Clock3 size={14} />{String(Math.floor(seconds / 60)).padStart(2,'0')}:{String(seconds % 60).padStart(2,'0')}</span></header><main className="checkout-layout"><section><p className="checkout-kicker">OPERACIÓN SEGURA · DEMO</p><h1>ÚLTIMO<br /><em>FOTOGRAMA.</em></h1><div className="operation-switch" aria-label="Tipo de operación"><button className={operation === 'reservation' ? 'is-active' : ''} onClick={() => { setOperation('reservation'); setAccepted(false); }}>RESERVAR</button><button className={operation === 'purchase' ? 'is-active' : ''} onClick={() => { setOperation('purchase'); setAccepted(false); }}>COMPRAR</button></div><div className="checkout-card"><div><span>CLIENTE</span><strong>{user?.name} · {user?.email}</strong></div><div><span>PELÍCULA</span><strong>{showing.movie?.title || showing.Pelicula?.titulo}</strong></div><div><span>FUNCIÓN</span><strong>{formatCinemaDate(showing.starts_at)} · {formatCinemaTime(showing.starts_at)}</strong></div><div><span>SALA / FORMATO</span><strong>{showing.room || showing.cinema_rooms?.name} · {showing.formatLabel || showing.format}</strong></div><div><span>ASIENTOS</span><strong>{seatIds.join(' · ')}</strong></div></div><label className="terms-check"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} /><span><Check size={14} /></span><p>Acepto confirmar esta {operation === 'reservation' ? 'reserva' : 'compra de demostración'}{operation === 'purchase' ? ' y entiendo que no se realizará ningún cobro.' : '.'}</p></label>{error && <p className="booking-error">{error}</p>}</section><aside className="checkout-total"><ShieldCheck size={28} /><p>RESUMEN</p><div><span>Cantidad</span><strong>{seatIds.length} ticket{seatIds.length === 1 ? '' : 's'}</strong></div><div><span>Precio unitario</span><strong>{formatCOP(unitPrice)}</strong></div><div><span>Servicio</span><strong>{formatCOP(0)}</strong></div><div className="checkout-total__grand"><span>TOTAL</span><strong>{formatCOP(hold.total)}</strong></div><button className="button-primary" disabled={!accepted || loading || seconds === 0} onClick={confirm}>{loading ? <LoaderCircle className="animate-spin" size={17} /> : <ShieldCheck size={17} />}CONFIRMAR {operation === 'reservation' ? 'RESERVA' : 'COMPRA'}</button><small>{operation === 'reservation' ? 'Las sillas quedarán reservadas.' : 'Transacción simulada. Las sillas quedarán vendidas.'}</small></aside></main></div>;
}
